// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIOaw8ji0WpuBHIwH9hat2emEIF2U61uo',
    appId: '1:993652224745:web:7d111c3b8b2866dfdb3678',
    messagingSenderId: '993652224745',
    projectId: 'voyage-a88c5',
    authDomain: 'voyage-a88c5.firebaseapp.com',
    databaseURL: 'https://voyage-a88c5-default-rtdb.firebaseio.com',
    storageBucket: 'voyage-a88c5.appspot.com',
    measurementId: 'G-8QT7K6GPGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYXyhH890eUS5kZ4x9mXG8AvZT2xEaxes',
    appId: '1:993652224745:android:0082dcea4be04975db3678',
    messagingSenderId: '993652224745',
    projectId: 'voyage-a88c5',
    databaseURL: 'https://voyage-a88c5-default-rtdb.firebaseio.com',
    storageBucket: 'voyage-a88c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDql3FKvu4VhKVdyxJW3Ve___bZizzHPzg',
    appId: '1:993652224745:ios:38af2c1691cb9b21db3678',
    messagingSenderId: '993652224745',
    projectId: 'voyage-a88c5',
    databaseURL: 'https://voyage-a88c5-default-rtdb.firebaseio.com',
    storageBucket: 'voyage-a88c5.appspot.com',
    iosBundleId: 'com.example.voyage',
  );

}